# Default Theme

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'238'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

#background tones
BASE03="16" #actually closer to 17, but 16 looks better
BASE02="236"
#content tones
BASE01="60"
BASE00="66"
BASE0="102"
BASE1="109"
#background tones
BASE2="224"
BASE3="230"
BASERED="124" #or 160
BASELIGHTLIGHTGRAY="248"
BASELIGHTGRAY="244"
BASEDARKGRAY="237"

#accent colors
YELLOW="136"
ORANGE="166"
MAGENTA="163"
VIOLET="62"
BLUE="32"
CYAN="36"
GREEN="100"
BLACK="233"

WHITE="255"
RED="196"

# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info ${BASERED} ${BLACK}" \
		"hostname ${BASELIGHTGRAY} ${BLACK}" \
		#"ifstat 30 255" \
		#"ifstat_sys 30 255" \
		#"lan_ip ${BASE02} ${GREEN} ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		#"wan_ip ${BASE02} ${BLUE}" \
		"vcs_branch ${BASEDARKGRAY} 247" \
		"vcs_compare ${BASERED} 255" \
		"vcs_staged ${BASERED} 255" \
		"vcs_modified ${BASERED} 255" \
		#"vcs_others 245 0" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		#"earthquake 3 0" \
		#"pwd ${BASERED} 255" \
		#"mailcount ${WHITE} ${RED}" \
		"now_playing 234 ${RED}" \
		#"cpu 240 136" \
		"load ${BASEDARKGRAY} 247" \
		#"tmux_mem_cpu_load 234 136" \
		"battery ${BASELIGHTGRAY} ${RED}" \
		#"weather ${BASE3} ${CYAN}" \
		#"xkb_layout 125 117" \
		"date_day ${BASELIGHTGRAY} ${BLACK}" \
		"date ${BASELIGHTGRAY} ${BLACK} ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"time ${BASELIGHTGRAY} ${BLACK} ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"utc_time 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
	)
fi
